services:
    Dominique92.Gym.listener:
        class: Dominique92\Gym\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@auth'
        tags:
            - { name: event.listener }
